export { HomePage as Home } from "./Home";
export { AuthenticationPage as Authentication } from "./Authentication";
export { LikedVideosPage as LikedVideos } from "./LikedVideos";
export { PlaylistPage as Playlist } from "./Playlist";
export { ProfilePage as Profile } from "./Profile";
export { WatchHistoryPage as WatchHistory } from "./WatchHistory";
export { WatchLaterPage as WatchLater } from "./WatchLater";
export { ExplorePage as Explore } from "./Explore";
export { VideosDetailsPage as VideosDetails } from "./VideosDetails";
